name: Deploy Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-prod:
    uses: ./.github/workflows/template-cd.yml
    with:
      environment_name: prod
      project_name: iac-bicep-demo
      sql_admin_login: sqladmin
    secrets:
      SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}