name: Deploy Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    uses: ./.github/workflows/template-cd.yml
    with:
      environment_name: prod
      project_name: iacdemo
      sql_admin_login: sqladminprod